# Generated by Django 6.0.6 on 2026-07-07 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bitki Adı')),
                ('soil_type', models.CharField(max_length=100, verbose_name='Toprak Türü')),
                ('watering_interval_days', models.IntegerField(verbose_name='Kaç Günde Bir Sulanmalı?')),
                ('last_watered_date', models.DateField(default=django.utils.timezone.now, verbose_name='Son Sulama Tarihi')),
            ],
        ),
    ]
