# Generated by Django 6.0.6 on 2026-07-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bitki Adı')),
                ('soil_type', models.CharField(max_length=100, verbose_name='İdeal Toprak Türü')),
                ('watering_interval_days', models.IntegerField(verbose_name='Varsayılan Sulama Sıklığı (Gün)')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name="Bitki Resim URL'i")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Bitki Hakkında Bilgi / Bakım Tüyoları')),
            ],
        ),
    ]
