# Generated by Django 6.0.6 on 2026-07-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_catalogplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogplant',
            name='min_stock_alert',
            field=models.IntegerField(default=5, verbose_name='Minimum Stok Uyarı Sınırı'),
        ),
        migrations.AddField(
            model_name='catalogplant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Satış Fiyatı'),
        ),
        migrations.AddField(
            model_name='catalogplant',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stok Adedi'),
        ),
    ]
